# Generated by Django 4.1.7 on 2023-03-11 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('main_image', models.ImageField(upload_to='house_services/%Y/%m/%d/', verbose_name='main_image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('data', models.JSONField(blank=True, default=dict, null=True, verbose_name='data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House_service',
                'verbose_name_plural': 'House_services',
            },
        ),
        migrations.CreateModel(
            name='House_serviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_services_images/%Y/%m/%d/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_service_images', to='house_services.house_service', verbose_name='house_service')),
            ],
            options={
                'verbose_name': 'House_service Image',
                'verbose_name_plural': 'House_service Images',
            },
        ),
    ]
