# Generated by Django 4.1.7 on 2023-03-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_service',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('InProcess', 'Inprocess'), ('Done', 'Done')], default='New', max_length=50),
        ),
    ]
